export const CREATE_SERVICES = "CREATE_SERVICES";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const DELETE_SERVICES = "DELETE_SERVICES";
export const FETCH_SERVICES_BEGIN = "FETCH_SERVICES_BEGIN";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_ERROR = "FETCH_SERVICES_ERROR";

export const CREATE_STAFFS = "CREATE_STAFFS";
export const UPDATE_STAFFS = "UPDATE_STAFFS";
export const DELETE_STAFFS = "DELETE_STAFFS";
export const FETCH_STAFF_BEGIN = "FETCH_STAFF_BEGIN";
export const FETCH_STAFF_SUCCESS = "FETCH_STAFF_SUCCCESS";
export const FETCH_STAFF_ERROR = "FETCH_STAFF_ERROR";

export const CREATE_CUSTOMERS = "CREATE_CUSTOMERS";
export const UPDATE_CUSTOMERS = "UPDATE_CUSTOMERS";
export const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
export const FETCH_CUSTOMER_BEGIN = "FETCH_CUSTOMER_BEGIN";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_ERROR = "FETCH_CUSTOMER_ERROR";

export const CREATE_BOOKING = "CREATE_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const FETCH_BOOKING_BEGIN = "FETCH_BOOKING_BEGIN";
export const FETCH_BOOKING_SUCCESS = "FETCH_BOOKING_SUCCESS";
export const FETCH_BOOKING_ERROR = "FETCH_BOOKING_ERROR";


export const CHANGE_PAGE = "CHANGE_PAGE";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_CONFIRM_MODAL = "OPEN_CONFIRM_MODAL";
export const CLOSE_CONFIRM_MODAL = "CLOSE_CONFIRM_MODAL";
