export const CREATE_SERVICES = "CREATE_SERVICES";
export const FETCH_SERVICES_BEGIN = "FETCH_SERVICES_BEGIN";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_ERROR = "FETCH_SERVICES_ERROR";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const DELETE_SERVICES = "DELETE_SERVICES";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
