export const CREATE_SERVICES = "CREATE_SERVICES";
export const FETCH_SERVICES_BEGIN = "FETCH_SERVICES_BEGIN";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_ERROR = "FETCH_SERVICES_ERROR";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const DELETE_SERVICES = "DELETE_SERVICES";

export const CREATE_STAFFS = "CREATE_STAFFS";
export const FETCH_STAFF_BEGIN = "FETCH_STAFF_BEGIN";
export const FETCH_STAFF_SUCCESS = "FETCH_STAFF_SUCCCESS";
export const FETCH_STAFF_ERROR = "FETCH_STAFF_ERROR";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
